version: '3'
services:
  web:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/test
  postgres:
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
