version: '3'
services:
  web:
    container_name: node
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - redis
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: test
      REDIS_PORT: 6379
  postgres:
    container_name: postgres
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always
